// generated by Fast Light User Interface Designer (fluid) version 1.0305

#include "window_vocoder.fl.h"

void WindowVocoderFltk::cb_Quit_i(Fl_Menu_*, void*) {
  WindowVocoderEvent e;
e.setExit();
cbWindowVocoder->doCallback(&e);
}
void WindowVocoderFltk::cb_Quit(Fl_Menu_* o, void* v) {
  ((WindowVocoderFltk*)(o->parent()->user_data()))->cb_Quit_i(o,v);
}

void WindowVocoderFltk::cb_About_i(Fl_Menu_*, void*) {
  makeWindowAbout()->show();
}
void WindowVocoderFltk::cb_About(Fl_Menu_* o, void* v) {
  ((WindowVocoderFltk*)(o->parent()->user_data()))->cb_About_i(o,v);
}

Fl_Menu_Item WindowVocoderFltk::menu_Menu[] = {
 {"File", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Open Configuration", 0,  0, 0, 16, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Save Configuration", 0,  0, 0, 144, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Preferences", 0,  0, 0, 144, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Quit", 0,  (Fl_Callback*)WindowVocoderFltk::cb_Quit, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Help", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"About", 0,  (Fl_Callback*)WindowVocoderFltk::cb_About, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

void WindowVocoderFltk::cb_Exit_i(Fl_Button*, void*) {
  WindowVocoderEvent e;
e.setExit();
cbWindowVocoder->doCallback(&e);
}
void WindowVocoderFltk::cb_Exit(Fl_Button* o, void* v) {
  ((WindowVocoderFltk*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_Exit_i(o,v);
}

#include <FL/Fl_Pixmap.H>
static const char *idata_exit[] = {
"24 24 2 1",
" \tc None",
".\tc #000000",
"                        ",
"                        ",
"                        ",
"                        ",
"    ...          ...    ",
"    ....        ....    ",
"    .....      .....    ",
"     .....    .....     ",
"      .....  .....      ",
"       ..........       ",
"        ........        ",
"         ......         ",
"         ......         ",
"        ........        ",
"       ..........       ",
"      .....  .....      ",
"     .....    .....     ",
"    .....      .....    ",
"    ....        ....    ",
"    ...          ...    ",
"                        ",
"                        ",
"                        ",
"                        "
};
static Fl_Image *image_exit() {
  static Fl_Image *image = new Fl_Pixmap(idata_exit);
  return image;
}

static const char *idata_vocoder[] = {
"168 32 2 1",
" \tc None",
".\tc #000000",
"                                                                             \
                                                                              \
             ",
"                                                                             \
                                                         ...                  \
             ",
"                    .                                                        \
                                                                              \
             ",
"                  ...         ..........         .........                   \
                                                       ....                   \
             ",
"                 ...             .......           .......                   \
                                                       ....                   \
             ",
"               ...                                                           \
                                                                              \
             ",
"              ...              ....              ...                         \
                                                     ...                      \
             ",
"             ...                ...              ..                          \
                                                    ....                      \
             ",
"            ...                                                              \
                                                                              \
             ",
"           ...                 ....            ..                            \
                                                   ...                        \
             ",
"          ...                  ....           ..                             \
                                                   ...                        \
             ",
"         ...                                                                 \
                                                                              \
             ",
"         ...                  ....          ..         .....   ....          \
...   ....       .....   ....           ....     ....         ....   ....   ..\
.....  ..... ",
"        ...                   ....         ...        ....      ....        .\
..     ....     ....      ....        ....       ....        ...     ....     \
 ...  ...... ",
"       ...                                                                   \
                                                                              \
             ",
"       ...                    ...        ..        ....         ...      ... \
      ...    ....         ...      ....        ....       ....       ...      \
... .        ",
"      ...                     ...        ..        ....         ....    .... \
             ....         ....     ....        ....       ...       ....      \
....         ",
"      ...                                                                    \
                                                                              \
             ",
"     ...                     ....     ...        ....          ....   ....   \
           ....          ....    ....        ....       ...       ....      ..\
..           ",
"     ...                     ....     ..        ....           ....   ....   \
          ....           ....   ....         ....      ....     ....        ..\
..           ",
"    ...                                                                      \
                                                                              \
             ",
"    ...                                                                      \
                                                                              \
             ",
"   ....                      ...   ..          ....          ....   ....     \
         ....          ....   ....        .....      ......               ....\
             ",
"   ....                      ...   ..          ...          ....    ....     \
         ...          ....    ....        .....      ....                 ... \
             ",
"   ...                                                                       \
                                                                              \
             ",
"  ....                                                                       \
                                                                              \
             ",
"  ....                      ......            ...         ....     ....      \
  ..    ...         ....     ....      .  ...   ..  .....        ..     ....  \
             ",
"  ....                      .....             ....       ....      .....     \
 ..     ....       ....      ....     .  ....   .    ....       ..      ...   \
             ",
"  ....                                                                       \
                                                                              \
             ",
"  ....                                                                       \
                                                                              \
             ",
"  ...                       ..                  ........             ......  \
          ........           .....       ....         .......         ....    \
             ",
"                                                                             \
                                                                              \
             "
};
static Fl_Image *image_vocoder() {
  static Fl_Image *image = new Fl_Pixmap(idata_vocoder);
  return image;
}

static const char *idata_vumeter_formant[] = {
"5 41 2 1",
" \tc None",
".\tc #000000",
".....",
".    ",
".... ",
".    ",
".    ",
"     ",
" ... ",
".   .",
".   .",
".   .",
" ... ",
"     ",
".... ",
".   .",
".... ",
".  . ",
".   .",
"     ",
".. ..",
".....",
". . .",
".   .",
".   .",
"     ",
" ... ",
".   .",
".....",
".   .",
".   .",
"     ",
".   .",
"..  .",
". . .",
".  ..",
".   .",
"     ",
".....",
"  .  ",
"  .  ",
"  .  ",
"  .  "
};
static Fl_Image *image_vumeter_formant() {
  static Fl_Image *image = new Fl_Pixmap(idata_vumeter_formant);
  return image;
}

static const char *idata_vumeter_carrier[] = {
"5 41 2 1",
" \tc None",
".\tc #000000",
" ....",
".    ",
".    ",
".    ",
" ....",
"     ",
" ... ",
".   .",
".....",
".   .",
".   .",
"     ",
".... ",
".   .",
".... ",
".  . ",
".   .",
"     ",
".... ",
".   .",
".... ",
".  . ",
".   .",
"     ",
"  .  ",
"  .  ",
"  .  ",
"  .  ",
"  .  ",
"     ",
".....",
".    ",
"...  ",
".    ",
".....",
"     ",
".... ",
".   .",
".... ",
".  . ",
".   ."
};
static Fl_Image *image_vumeter_carrier() {
  static Fl_Image *image = new Fl_Pixmap(idata_vumeter_carrier);
  return image;
}

void WindowVocoderFltk::cb_150Hz_i(Fl_Slider* o, void*) {
  ((WindowVocoderBand *)o->parent())->changed();
}
void WindowVocoderFltk::cb_150Hz(Fl_Slider* o, void* v) {
  ((WindowVocoderFltk*)(o->parent()->parent()->user_data()))->cb_150Hz_i(o,v);
}

void WindowVocoderFltk::cb__i(Fl_Dial* o, void*) {
  ((WindowVocoderBand *)o->parent())->changed();
}
void WindowVocoderFltk::cb_(Fl_Dial* o, void* v) {
  ((WindowVocoderFltk*)(o->parent()->parent()->user_data()))->cb__i(o,v);
}

void WindowVocoderFltk::cb_R_i(Fl_Button* o, void*) {
  WindowVocoderBand *b=(WindowVocoderBand *)o->parent();
b->setPanning(0.0);
b->setVolume(1.0);
}
void WindowVocoderFltk::cb_R(Fl_Button* o, void* v) {
  ((WindowVocoderFltk*)(o->parent()->parent()->user_data()))->cb_R_i(o,v);
}

void WindowVocoderFltk::cb_OK_i(Fl_Button* o, void*) {
  Fl_Double_Window *w=(Fl_Double_Window *)o->parent();
w->hide();
delete w;
}
void WindowVocoderFltk::cb_OK(Fl_Button* o, void* v) {
  ((WindowVocoderFltk*)(o->parent()->user_data()))->cb_OK_i(o,v);
}

WindowVocoderFltk::WindowVocoderFltk(WindowVocoder* p) {
  // Init
  
  // set corresponding class to this widget class
  cbWindowVocoder=p;
}

Fl_Double_Window* WindowVocoderFltk::makeWindow() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(700, 204);
    w = o; if (w) {/* empty */}
    o->user_data((void*)(this));
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 700, 20, "Menu");
      o->menu(menu_Menu);
    } // Fl_Menu_Bar* o
    { Fl_Group* o = new Fl_Group(0, 20, 700, 184, "Contents");
      o->labeltype(FL_NO_LABEL);
      { Fl_Group* o = new Fl_Group(0, 20, 700, 40, "Toprow");
        o->labeltype(FL_NO_LABEL);
        { Fl_Group* o = new Fl_Group(0, 20, 56, 40, "ButtonBarGroup");
          o->labeltype(FL_NO_LABEL);
          { Fl_Button* o = new Fl_Button(0, 20, 45, 40, "Exit");
            o->image( image_exit() );
            o->callback((Fl_Callback*)cb_Exit);
          } // Fl_Button* o
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(455, 20, 245, 40);
          o->image( image_vocoder() );
          o->align(Fl_Align(FL_ALIGN_CENTER));
          { Fl_Group* o = new Fl_Group(650, 45, 45, 15, "V0.00");
            o->labelsize(9);
            o->align(Fl_Align(FL_ALIGN_TOP|FL_ALIGN_INSIDE));
            o->label("V" VERSION);
            o->end();
          } // Fl_Group* o
          o->end();
        } // Fl_Group* o
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(0, 64, 60, 140, "Vumeters");
        o->labeltype(FL_NO_LABEL);
        { WindowVocoderVumeter* o = new WindowVocoderVumeter(15, 69, 8, 130, "VUmeter formant");
          o->box(FL_NO_BOX);
          o->color(FL_BACKGROUND_COLOR);
          o->selection_color(FL_BACKGROUND_COLOR);
          o->labeltype(FL_NO_LABEL);
          o->labelfont(0);
          o->labelsize(14);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->align(Fl_Align(FL_ALIGN_TOP));
          o->when(FL_WHEN_RELEASE);
          vumeterFormant=o;
          o->setDirection(false);
          o->setTilesize(12);
          o->end();
        } // WindowVocoderVumeter* o
        { WindowVocoderVumeter* o = new WindowVocoderVumeter(45, 69, 8, 130, "VUmeter carrier");
          o->box(FL_NO_BOX);
          o->color(FL_BACKGROUND_COLOR);
          o->selection_color(FL_BACKGROUND_COLOR);
          o->labeltype(FL_NO_LABEL);
          o->labelfont(0);
          o->labelsize(14);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->align(Fl_Align(FL_ALIGN_TOP));
          o->when(FL_WHEN_RELEASE);
          vumeterCarrier=o;
          o->setDirection(false);
          o->setTilesize(12);
          o->end();
        } // WindowVocoderVumeter* o
        { Fl_Group* o = new Fl_Group(3, 145, 10, 50);
          o->image( image_vumeter_formant() );
          o->align(Fl_Align(FL_ALIGN_BOTTOM|FL_ALIGN_INSIDE));
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(33, 145, 10, 50);
          o->image( image_vumeter_carrier() );
          o->align(Fl_Align(FL_ALIGN_BOTTOM|FL_ALIGN_INSIDE));
          o->end();
        } // Fl_Group* o
        o->end();
      } // Fl_Group* o
      { WindowVocoderBands* o = new WindowVocoderBands(60, 64, 640, 140, "Bands");
        o->box(FL_NO_BOX);
        o->color(FL_BACKGROUND_COLOR);
        o->selection_color(FL_BACKGROUND_COLOR);
        o->labeltype(FL_NO_LABEL);
        o->labelfont(0);
        o->labelsize(14);
        o->labelcolor(FL_FOREGROUND_COLOR);
        o->align(Fl_Align(FL_ALIGN_TOP));
        o->when(FL_WHEN_RELEASE);
        bands=o;
        o->end();
      } // WindowVocoderBands* o
      o->end();
    } // Fl_Group* o
    o->end();
    o->resizable(o);
  } // Fl_Double_Window* o
  return w;
}

Fl_Double_Window* WindowVocoderFltk::makeBand() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(40, 140);
    w = o; if (w) {/* empty */}
    o->user_data((void*)(this));
    { WindowVocoderBand* o = new WindowVocoderBand(0, 0, 40, 140, "Band");
      o->box(FL_UP_BOX);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NO_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->align(Fl_Align(FL_ALIGN_TOP));
      o->when(FL_WHEN_RELEASE);
      { Fl_Slider* o = new Fl_Slider(10, 13, 20, 75, "150Hz");
        o->labelsize(10);
        o->callback((Fl_Callback*)cb_150Hz, (void*)(o));
        o->align(Fl_Align(FL_ALIGN_TOP));
      } // Fl_Slider* o
      { Fl_Dial* o = new Fl_Dial(10, 96, 20, 20);
        o->step(0.01);
        o->value(0.5);
        o->callback((Fl_Callback*)cb_, (void*)(o));
      } // Fl_Dial* o
      { Fl_Button* o = new Fl_Button(10, 123, 20, 10, "R");
        o->callback((Fl_Callback*)cb_R, (void*)(o));
      } // Fl_Button* o
      o->end();
    } // WindowVocoderBand* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}

Fl_Double_Window* WindowVocoderFltk::makeWindowAbout() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(390, 275);
    w = o; if (w) {/* empty */}
    o->user_data((void*)(this));
    o->align(Fl_Align(FL_ALIGN_TOP|FL_ALIGN_INSIDE));
    { Fl_Text_Display* o = new Fl_Text_Display(30, 50, 330, 165);
      o->textsize(12);
    } // Fl_Text_Display* o
    { Fl_Button* o = new Fl_Button(160, 230, 80, 25, "OK");
      o->callback((Fl_Callback*)cb_OK, (void*)(o));
    } // Fl_Button* o
    { Fl_Group* o = new Fl_Group(0, 0, 390, 40);
      o->image( image_vocoder() );
      o->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
      o->end();
      Fl_Group::current()->resizable(o);
    } // Fl_Group* o
    o->end();
  } // Fl_Double_Window* o
  // set text
  Fl_Text_Display *text=(Fl_Text_Display *)w->child(0);
  Fl_Text_Buffer *buffer=new Fl_Text_Buffer(1024);
  buffer->append("Vocoder V" VERSION "\n© 2007 Achim Settelmeier\n\nIdea, code and design:\n  Achim Settelmeier <vocoder@m1.sirlab.de>\n\n\n\nhttp://sirlab.de/linux/");
  text->buffer(buffer);
  return w;
}
