// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef window_vocoder_fl_h
#define window_vocoder_fl_h
#include <FL/Fl.H>
#include "window_vocoder.h"
#include "window_vocoder_band.h"
#include "window_vocoder_bands.h"
#include "window_vocoder_vumeter.h"
class WindowVocoder;
class WindowVocoderBand;
class WindowVocoderBands;
class WindowVocoderVumeter;
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Slider.H>
#include <FL/Fl_Dial.H>
#include <FL/Fl_Text_Display.H>

class WindowVocoderFltk {
  WindowVocoder *cbWindowVocoder; 
public:
  WindowVocoderBands *bands; 
  WindowVocoderVumeter *vumeterFormant, *vumeterCarrier; 
  WindowVocoderFltk(WindowVocoder* p);
  Fl_Double_Window* makeWindow();
  static Fl_Menu_Item menu_Menu[];
private:
  inline void cb_Quit_i(Fl_Menu_*, void*);
  static void cb_Quit(Fl_Menu_*, void*);
  inline void cb_About_i(Fl_Menu_*, void*);
  static void cb_About(Fl_Menu_*, void*);
  inline void cb_Exit_i(Fl_Button*, void*);
  static void cb_Exit(Fl_Button*, void*);
public:
  Fl_Double_Window* makeBand();
private:
  inline void cb_150Hz_i(Fl_Slider*, void*);
  static void cb_150Hz(Fl_Slider*, void*);
  inline void cb__i(Fl_Dial*, void*);
  static void cb_(Fl_Dial*, void*);
  inline void cb_R_i(Fl_Button*, void*);
  static void cb_R(Fl_Button*, void*);
public:
  Fl_Double_Window* makeWindowAbout();
private:
  inline void cb_OK_i(Fl_Button*, void*);
  static void cb_OK(Fl_Button*, void*);
};
#endif
